### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by JohnCorby** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#1]
![image](https://user-images.githubusercontent.com/26337121/213818819-34e44d59-54d3-4ed1-82c4-360486457768.png)
![image](https://user-images.githubusercontent.com/26337121/213818829-3a57e778-58c6-4882-9db3-16b2e28c4dee.png)

**Comment by JohnCorby** [comment]
second one might be fixed in new version, i havent checked yet

**Comment by StreetlightsBehindTheTrees** [comment]
I did fix the second one. Hopefully all spelling errors will be fixed in v1.0.3.
