### ISSUE TITLE
Asking for a music pls ฅ(=චᆽච=ฅ)

### ISSUE THREAD

**Issue by Zreox233** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#11]
I am a four eyed fish from China, and I am using a translator to translate these sentences. Therefore, I apologize for any grammar errors
       Can I ask you for the background music at the Northern Observatory? It is so epic and grand, but the effect of converting screen recording to MP3 playback will eventually be compromised. Can I ask you for this music file. If possible, thank you very much.

**Comment by TRSasasusu** [comment]
You can listen to the sound tracks in [YouTube](https://youtu.be/Qs1-CSQ2hgo?si=NrtxRhenXbA7S8-0) (uploaded by the author).

Also, you can get the original `.wav` file from the asset bundle files.
The music of the Northern Observatory is `ost_Datura.wav` contained in [extramusicbundle](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/main/extramusicbundle).

## How to extract music files from an asset bundle file?

You can use [AssetStudio](https://github.com/Perfare/AssetStudio).
Its usage is so simple:

1. Drug and drop the asset bundle file (`extramusicbundle`) to AssetStudio.
2. Use `Filter Type` to filter in `Audio Clip`.
3. You can find `ost_Datura.wav` in `Asset List`.
4. Export it!

**Comment by Zreox233** [comment]
@TRSasasusu thank you so much，have a nice day <(^^,)>
