### ISSUE TITLE
Neck dislocation 

### ISSUE THREAD

**Issue by Fern-Leaves** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#16]
Friend's neck dislocates when I get close![download (5) (7).jpeg](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/assets/56755065/5757b1bb-6564-4b26-ad2a-56f767e26cd0)

![download (5) (8).jpeg](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/assets/56755065/8c1b7695-6700-4e52-9062-17880f2a7acb)

List of other installed mods:
- Achievements+
- Colour Cameras
- Common Camera Utilities
- Custom Ship Log Mode
- Cut Achievements
- Daydream
- Enable Meditation 
- General Enhancements 
- Global SSR
- Glowstick Bracelets
- Hug Mod
- Immersion 
- Menu Framework 
- New Horizons 
- Proud Hearthians 
- Quality of Life Features
- Quantum Moon Orbit Line
- Reactive Hearthians 
- Secret Settings
- Ship Light Toggle
- Signals+
- Silly Filters 
- Suit Log
- Vanilla Fix
- Voice Acting Mod

**Comment by xen-42** [comment]
I bet this is because of daydream, likely Friend's looking-at-the-player animation has a specific vector hard-coded to be "up" which is no longer true when the Dreamworld is rotated to put the sun in the sky

**Comment by xen-42** [comment]
Fixed by #20
