### ISSUE TITLE
Italian translation correction.

### ISSUE THREAD

**Issue by NerYtheLonesomeHearthian** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#17]
I recently did a complete playthrough of The Outsider with a friend, and i noticed a couple of spelling mistakes in the translation i made. Here i upload the corrected file (it again has been turned from a .xml into a .txt for the upload). 
Thank you.
[italian.txt](https://github.com/user-attachments/files/15806190/italian.txt)

**Comment by TRSasasusu** [comment]
@NerYtheLonesomeHearthian Thanks! It is released in [v1.1.4](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/releases/tag/v1.1.4)
