### ISSUE TITLE
(Nitpick) Wrong Color Space

### ISSUE THREAD

**Issue by JohnCorby** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#2]
![image](https://user-images.githubusercontent.com/26337121/213819013-e7ff1019-792d-4f54-91ef-860595fcd57a.png)
![image](https://user-images.githubusercontent.com/26337121/213819101-041d6224-6bed-42b0-933a-6108f2f58820.png)

Specular looks grey because your color space is Gamma instead of Linear. Changing it in editor and reexporting your bundles should fix the issue.

**Comment by JohnCorby** [comment]
If your color space is already linear then just close this issue and disregard me as being silly

**Comment by StreetlightsBehindTheTrees** [comment]
It is gamma, but I don't know if I want to change it, at this point. Thanks, anyway.
