### ISSUE TITLE
DB atmo sometimes makes sun and other planets look dark on some loops

### ISSUE THREAD

**Issue by JohnCorby** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#3]
![image](https://user-images.githubusercontent.com/26337121/213822018-ae8439c8-fcbb-41d3-9006-b9eef39e7ef7.png)

no clue why

**Comment by StreetlightsBehindTheTrees** [comment]
Not sure why either. But it is DARK Bramble, after all.
