### ISSUE TITLE
Can't read ATP to DB stone from ATP

### ISSUE THREAD

**Issue by GameWyrm** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#4]
![image](https://user-images.githubusercontent.com/78181444/213825162-6c4d8301-ad5b-42d2-b929-6ad334a4394a.png)
I can't read this Nomai text as I can't pull up my translator to it. The other stones in this area and the mod (that I've found so far) work fine.

No other mods enabled. Version 1.0.2.

**Comment by StreetlightsBehindTheTrees** [comment]
This text is very annoying, as it seems completely random on if it works or not, sorry. (It's just the non-broken version of a stone you should already have read, so it's not a huge problem, but still annoying.)

**Comment by TRSasasusu** [comment]
Solved!
