### ISSUE TITLE
Oversight: Ghost Matter in Datura's House still damages you when submerged

### ISSUE THREAD

**Issue by GameWyrm** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#6]
Ghost Matter is unable to penetrate water and becomes instantly inert when submerged. This can be seen in the tunnel in Gabbro's Island: when it is submerged, the Ghost Matter within will no longer damage you.

I thought that this was the way I was supposed to get the scroll within Datura's House, by waiting for it to be carried into Giant's Deep and then grabbing the scroll really quick while the house was underwater. While it's nice to have this bit of confirmation that this probably isn't intended, for consistency's sake, this should be addressed. (And if it is the intended solution, well, there you go, it's a bug that it can sometimes still burn you).

**Comment by StreetlightsBehindTheTrees** [comment]
It is not the intended solution, as you likely would not be able to read it. I may fix this soon.

**Comment by GameWyrm** [comment]
Having figured out the correct solution, I feel pretty dumb, but I still think this should be fixed. Perhaps by making his house linger just a little bit longer, so it hits GD late enough to make it obvious you don't have time, or perhaps making it hit GD even sooner, making it a valid solution.

**Comment by StreetlightsBehindTheTrees** [comment]
Ghost Matter should be fixed in the next update.
