### ISSUE TITLE
[Question]About translation

### ISSUE THREAD

**Issue by solitary-sails** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#7]
Is there any plan to translate this mod to other languages, or accept text translated by the community.

**Comment by StreetlightsBehindTheTrees** [comment]
Currently, I'm exhausted and need a break for a few weeks. Though, if anyone is really wanting to make a translation, they can, it will just be a while before they are added.

**Comment by Ash-Twin** [comment]
> Currently, I'm exhausted and need a break for a few weeks. Though, if anyone is really wanting to make a translation, they can, it will just be a while before they are added.

Dont get burnt out bro! I am willing to help on localization too.

**Comment by solitary-sails** [comment]
Then I'll wait for you to take a break first. If you have further plans in the future, I will be happy to do my little bit.

**Comment by solitary-sails** [comment]
> Currently, I'm exhausted and need a break for a few weeks. Though, if anyone is really wanting to make a translation, they can, it will just be a while before they are added.

Then I'll wait for you to take a break first. If you have further plans in the future, I will be happy to do my little bit.
