### ISSUE TITLE
Projection from ATP to DB causes teleportation

### ISSUE THREAD

**Issue by Tayrtahn** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#9]
Grabbing the new projection stone in the ATP (connected to DB) and placing it in the nearby projection system causes the player to be warped to a point just outside one of the entrances into Dark Bramble's interior. The usual projection effects are not shown, and moving away does not return the player to the ATP.

See video here: https://www.youtube.com/watch?v=I6bEeUYop3Q

**Comment by StreetlightsBehindTheTrees** [comment]
Thanks. I don't know if I'll be able to solve this issue however, as I don't know what is causing it, sorry.
